version: '2'

services:
  web:
    build:
      context: .
    container_name: deepl
    image: devockr/deepl
    environment:
      PORT: ${PORT:-8000}
    ports:
      - ${PORT:-8000}:${PORT:-8000}
