version: '2'

services:
  web:
    build:
      context: .
    container_name: deepl
    image: devockr/deepl
    environment:
      PORT: "${PORT:-8080}"
    ports:
      - "${PORT:-8080}:${PORT:-8080}"
